module.exports = [
  'USE_NORMALS',
  'USE_TANGENTS',
  'USE_TEX_COORDS',

  'USE_INSTANCED_OFFSET',
  'USE_INSTANCED_SCALE',
  'USE_INSTANCED_ROTATION',

  'USE_VERTEX_COLORS',
  'USE_INSTANCED_COLOR',

  'USE_BASE_COLOR_MAP',
  'USE_EMISSIVE_COLOR_MAP',
  'USE_NORMAL_MAP',
  'USE_DISPLACEMENT_MAP',

  'USE_AO',
  'USE_OCCLUSION_MAP',
  'USE_ALPHA_TEST',
  'USE_ALPHA_MAP',

  'USE_SKIN',
  'USE_REFLECTION_PROBES',
  'USE_BLEND',
  'USE_TONEMAPPING',

  'USE_UNLIT_WORKFLOW',
  'USE_METALLIC_ROUGHNESS_WORKFLOW',
  'USE_METALLIC_ROUGHNESS_MAP',
  'USE_METALLIC_MAP',
  'USE_ROUGHNESS_MAP',
  'USE_SPECULAR_GLOSSINESS_WORKFLOW',
  'USE_DIFFUSE_MAP',
  'USE_SPECULAR_GLOSSINESS_MAP',

  'DEPTH_PASS_ONLY',
  'DEPTH_PRE_PASS_ONLY',
  'SHADOW_QUALITY',
  'USE_DRAW_BUFFERS',

  'NUM_AMBIENT_LIGHTS',
  'NUM_DIRECTIONAL_LIGHTS',
  'NUM_POINT_LIGHTS',
  'NUM_SPOT_LIGHTS',
  'NUM_AREA_LIGHTS'
]
